-- Daniya secure application schema for the NEW dedicated Supabase project.
-- Apply with `supabase db push` after linking the correct project.

create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  name_en text,
  name_fr text,
  description text,
  description_en text,
  description_fr text,
  category text not null,
  price numeric(12,2) not null,
  image text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.advertisements (
  id bigint generated by default as identity primary key,
  image_url text not null,
  link text,
  created_at timestamptz not null default now()
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  translation_en text,
  translation_fr text,
  category text not null default 'products',
  media_type text not null default 'image',
  storage_path text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role = 'admin'),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  customer_address text,
  notes text,
  total_amount numeric(12,2) not null default 0,
  status text not null default 'new' check (status in ('new','confirmed','preparing','completed','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  product_category text,
  unit_price numeric(12,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity between 1 and 50),
  line_total numeric(12,2) generated always as (round(unit_price * quantity, 2)) stored,
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id uuid primary key default gen_random_uuid(),
  event_type text not null check (event_type in (
    'page_view','product_view','product_click','product_search','category_filter',
    'add_to_cart','remove_from_cart','cart_view','checkout_started','order_created','whatsapp_order_opened'
  )),
  product_id bigint references public.products(id) on delete set null,
  category text,
  page text,
  session_id uuid,
  language text check (language in ('ar','en','fr')),
  device_type text check (device_type in ('mobile','tablet','desktop')),
  referrer text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint analytics_metadata_object check (jsonb_typeof(metadata) = 'object'),
  constraint analytics_metadata_size check (octet_length(metadata::text) <= 2048)
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.rate_limit_buckets (
  scope text not null,
  key_hash text not null,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 1 check (request_count > 0),
  primary key (scope, key_hash)
);

-- Normalize known legacy category spellings without deleting unknown legacy data.
update public.products set category = 'food' where lower(trim(category)) in ('food items', 'fooditems');
update public.products set category = 'oils' where lower(trim(category)) in ('natural oils', 'naturaloils', 'oil');
update public.products set category = lower(trim(category)) where lower(trim(category)) in ('dates','honey','nuts','spices','food','oils');

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'products_price_nonnegative') then
    alter table public.products add constraint products_price_nonnegative check (price >= 0 and price <= 100000000) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'products_canonical_category') then
    alter table public.products add constraint products_canonical_category check (category in ('dates','honey','nuts','spices','food','oils')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'gallery_media_type_check') then
    alter table public.gallery add constraint gallery_media_type_check check (media_type in ('image','video')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'products_image_http') then
    alter table public.products add constraint products_image_http check (image ~* '^https?://') not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'advertisements_image_http') then
    alter table public.advertisements add constraint advertisements_image_http check (image_url ~* '^https?://') not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'advertisements_link_http') then
    alter table public.advertisements add constraint advertisements_link_http check (link is null or link = '' or link ~* '^https?://') not valid;
  end if;
end $$;

create index if not exists products_category_idx on public.products(category);
create index if not exists products_created_at_idx on public.products(created_at desc);
create index if not exists advertisements_created_at_idx on public.advertisements(created_at desc);
create index if not exists gallery_category_created_idx on public.gallery(category, created_at desc);
create index if not exists contacts_created_at_idx on public.contacts(created_at desc);
create index if not exists orders_status_created_idx on public.orders(status, created_at desc);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists order_items_product_idx on public.order_items(product_id);
create index if not exists analytics_created_type_idx on public.analytics_events(created_at desc, event_type);
create index if not exists analytics_product_created_idx on public.analytics_events(product_id, created_at desc) where product_id is not null;
create index if not exists analytics_session_created_idx on public.analytics_events(session_id, created_at desc) where session_id is not null;
create index if not exists analytics_category_created_idx on public.analytics_events(category, created_at desc) where category is not null;
create index if not exists audit_created_idx on public.admin_audit_logs(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists admin_users_set_updated_at on public.admin_users;
create trigger admin_users_set_updated_at before update on public.admin_users for each row execute function public.set_updated_at();
drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders for each row execute function public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_catalog
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid() and role = 'admin' and active = true
  );
$$;

revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated, service_role;

create or replace function public.consume_rate_limit(
  p_scope text,
  p_key_hash text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  current_bucket public.rate_limit_buckets%rowtype;
begin
  if p_scope !~ '^[a-z_]{2,40}$' or length(p_key_hash) <> 64 or p_limit < 1 or p_limit > 1000 or p_window_seconds < 10 or p_window_seconds > 86400 then
    return false;
  end if;

  select * into current_bucket from public.rate_limit_buckets
  where scope = p_scope and key_hash = p_key_hash for update;

  if not found then
    insert into public.rate_limit_buckets(scope, key_hash) values (p_scope, p_key_hash);
    return true;
  end if;

  if current_bucket.window_started_at + make_interval(secs => p_window_seconds) <= now() then
    update public.rate_limit_buckets set window_started_at = now(), request_count = 1
    where scope = p_scope and key_hash = p_key_hash;
    return true;
  end if;

  if current_bucket.request_count >= p_limit then return false; end if;
  update public.rate_limit_buckets set request_count = request_count + 1
  where scope = p_scope and key_hash = p_key_hash;
  return true;
end;
$$;

revoke all on function public.consume_rate_limit(text,text,integer,integer) from public, anon, authenticated;
grant execute on function public.consume_rate_limit(text,text,integer,integer) to service_role;

create or replace function public.submit_contact_internal(
  p_name text,
  p_email text,
  p_phone text,
  p_message text
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare new_id bigint;
begin
  if length(trim(coalesce(p_name, ''))) not between 2 and 100
     or length(coalesce(p_email, '')) > 160
     or length(coalesce(p_phone, '')) > 30
     or length(trim(coalesce(p_message, ''))) not between 5 and 2000
     or coalesce(p_email, '') !~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception using errcode = '22023', message = 'invalid contact payload';
  end if;
  insert into public.contacts(name,email,phone,message)
  values (trim(p_name), nullif(trim(p_email), ''), nullif(trim(p_phone), ''), trim(p_message))
  returning id into new_id;
  return new_id;
end;
$$;

revoke all on function public.submit_contact_internal(text,text,text,text) from public, anon, authenticated;
grant execute on function public.submit_contact_internal(text,text,text,text) to service_role;

create or replace function public.create_order_internal(
  p_customer_name text,
  p_customer_phone text,
  p_customer_address text,
  p_notes text,
  p_items jsonb,
  p_language text default 'ar',
  p_session_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  new_order public.orders%rowtype;
  item jsonb;
  product public.products%rowtype;
  item_quantity integer;
  item_product_id bigint;
  running_total numeric(12,2) := 0;
  seen_ids bigint[] := array[]::bigint[];
  response_items jsonb;
  product_label text;
begin
  if length(trim(coalesce(p_customer_name, ''))) not between 2 and 100
     or length(trim(coalesce(p_customer_phone, ''))) not between 6 and 30
     or length(coalesce(p_customer_address, '')) > 300
     or length(coalesce(p_notes, '')) > 1000
     or p_language not in ('ar','en','fr')
     or jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) not between 1 and 25 then
    raise exception using errcode = '22023', message = 'invalid order payload';
  end if;

  insert into public.orders(customer_name, customer_phone, customer_address, notes, status, total_amount)
  values (trim(p_customer_name), trim(p_customer_phone), nullif(trim(p_customer_address), ''), nullif(trim(p_notes), ''), 'new', 0)
  returning * into new_order;

  for item in select value from jsonb_array_elements(p_items) loop
    begin
      item_product_id := (item ->> 'product_id')::bigint;
      item_quantity := (item ->> 'quantity')::integer;
    exception when others then
      raise exception using errcode = '22023', message = 'invalid order item';
    end;
    if item_quantity not between 1 and 50 or item_product_id = any(seen_ids) then
      raise exception using errcode = '22023', message = 'invalid order item';
    end if;
    seen_ids := array_append(seen_ids, item_product_id);
    select * into product from public.products where id = item_product_id for share;
    if not found or product.price < 0 or product.price > 100000000 then
      raise exception using errcode = '22023', message = 'product unavailable';
    end if;
    product_label := case p_language
      when 'en' then coalesce(nullif(trim(product.name_en), ''), product.name)
      when 'fr' then coalesce(nullif(trim(product.name_fr), ''), nullif(trim(product.name_en), ''), product.name)
      else coalesce(nullif(trim(product.name), ''), product.name_en, product.name_fr)
    end;
    insert into public.order_items(order_id, product_id, product_name, product_category, unit_price, quantity)
    values (new_order.id, product.id, product_label, product.category, product.price, item_quantity);
    running_total := running_total + round(product.price * item_quantity, 2);
  end loop;

  if running_total <= 0 or running_total > 100000000 then
    raise exception using errcode = '22023', message = 'invalid order total';
  end if;
  update public.orders set total_amount = running_total where id = new_order.id returning * into new_order;

  insert into public.analytics_events(event_type, page, session_id, language, metadata)
  values ('order_created', '/checkout', p_session_id, p_language, jsonb_build_object('order_id', new_order.id));

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', oi.id, 'product_id', oi.product_id, 'product_name', oi.product_name,
    'unit_price', oi.unit_price, 'quantity', oi.quantity, 'line_total', oi.line_total
  ) order by oi.id), '[]'::jsonb) into response_items
  from public.order_items oi where oi.order_id = new_order.id;

  return jsonb_build_object(
    'id', new_order.id, 'customer_name', new_order.customer_name,
    'customer_phone', new_order.customer_phone, 'customer_address', new_order.customer_address,
    'notes', new_order.notes, 'total_amount', new_order.total_amount,
    'status', new_order.status, 'created_at', new_order.created_at, 'items', response_items
  );
end;
$$;

revoke all on function public.create_order_internal(text,text,text,text,jsonb,text,uuid) from public, anon, authenticated;
grant execute on function public.create_order_internal(text,text,text,text,jsonb,text,uuid) to service_role;

create or replace function public.audit_admin_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare row_id text; action_name text; details jsonb := '{}'::jsonb;
begin
  if not public.is_admin() then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;
  if tg_op = 'DELETE' then row_id := old.id::text; else row_id := new.id::text; end if;
  action_name := tg_table_name || '_' || lower(tg_op);
  if tg_table_name = 'orders' and tg_op = 'UPDATE' then
    details := jsonb_build_object('old_status', old.status, 'new_status', new.status);
  end if;
  insert into public.admin_audit_logs(admin_user_id, action, entity_type, entity_id, metadata)
  values (auth.uid(), action_name, tg_table_name, row_id, details);
  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

revoke all on function public.audit_admin_change() from public, anon, authenticated;

do $$
declare table_name text;
begin
  foreach table_name in array array['products','advertisements','gallery','contacts','orders'] loop
    execute format('drop trigger if exists audit_admin_%I on public.%I', table_name, table_name);
    execute format('create trigger audit_admin_%I after insert or update or delete on public.%I for each row execute function public.audit_admin_change()', table_name, table_name);
  end loop;
end $$;

create or replace function public.admin_dashboard_summary()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_catalog
as $$
declare day_start timestamptz; result jsonb;
begin
  if not public.is_admin() then raise exception using errcode = '42501', message = 'not authorized'; end if;
  day_start := date_trunc('day', now() at time zone 'Africa/Djibouti') at time zone 'Africa/Djibouti';
  select jsonb_build_object(
    'visitors_today', (select count(distinct session_id) from public.analytics_events where event_type = 'page_view' and created_at >= day_start and session_id is not null),
    'orders_today', (select count(*) from public.orders where created_at >= day_start),
    'revenue_today', (select coalesce(sum(total_amount),0) from public.orders where created_at >= day_start and status <> 'cancelled'),
    'new_orders', (select count(*) from public.orders where status = 'new'),
    'total_products', (select count(*) from public.products),
    'total_contacts', (select count(*) from public.contacts),
    'most_viewed_product', (select product_id from public.analytics_events where event_type = 'product_view' and product_id is not null group by product_id order by count(*) desc limit 1),
    'best_selling_product', (select product_id from public.order_items oi join public.orders o on o.id = oi.order_id where o.status <> 'cancelled' group by product_id order by sum(quantity) desc nulls last limit 1),
    'recent_orders', (select coalesce(jsonb_agg(row_to_json(x)), '[]'::jsonb) from (select id,customer_name,total_amount,status,created_at from public.orders order by created_at desc limit 6) x),
    'recent_contacts', (select coalesce(jsonb_agg(row_to_json(x)), '[]'::jsonb) from (select id,name,message,created_at from public.contacts order by created_at desc limit 6) x)
  ) into result;
  return result;
end;
$$;

revoke all on function public.admin_dashboard_summary() from public, anon;
grant execute on function public.admin_dashboard_summary() to authenticated;

create or replace function public.admin_analytics_report(p_from timestamptz, p_to timestamptz)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_catalog
as $$
declare result jsonb;
begin
  if not public.is_admin() then raise exception using errcode = '42501', message = 'not authorized'; end if;
  if p_from is null or p_to is null or p_from > p_to or p_to - p_from > interval '366 days' then
    raise exception using errcode = '22023', message = 'invalid date range';
  end if;

  with behavior as (
    select product_id,
      count(*) filter (where event_type = 'product_view')::int views,
      count(*) filter (where event_type = 'product_click')::int clicks,
      count(*) filter (where event_type = 'add_to_cart')::int cart_adds,
      count(*) filter (where event_type = 'remove_from_cart')::int cart_removals
    from public.analytics_events where created_at between p_from and p_to and product_id is not null group by product_id
  ), sales as (
    select oi.product_id, count(distinct oi.order_id)::int orders, sum(oi.quantity)::int ordered_units, coalesce(sum(oi.line_total),0) revenue
    from public.order_items oi join public.orders o on o.id = oi.order_id
    where o.created_at between p_from and p_to and o.status <> 'cancelled' and oi.product_id is not null group by oi.product_id
  ), product_report as (
    select p.id product_id, p.name, p.name_en, p.name_fr,
      coalesce(b.views,0) views, coalesce(b.clicks,0) clicks, coalesce(b.cart_adds,0) cart_adds,
      coalesce(b.cart_removals,0) cart_removals, coalesce(s.ordered_units,0) ordered_units,
      coalesce(s.orders,0) orders, coalesce(s.revenue,0) revenue,
      round(coalesce(b.cart_adds * 100.0 / nullif(b.views,0),0),1) view_to_cart,
      round(coalesce(s.orders * 100.0 / nullif(b.cart_adds,0),0),1) cart_to_order,
      round(coalesce(s.orders * 100.0 / nullif(b.views,0),0),1) overall_conversion
    from public.products p left join behavior b on b.product_id = p.id left join sales s on s.product_id = p.id
  ), daily as (
    select d::date as "day",
      (select count(distinct e.session_id) from public.analytics_events e where e.event_type='page_view' and e.session_id is not null and e.created_at >= d and e.created_at < d + interval '1 day')::int visitors,
      (select count(*) from public.orders o where o.created_at >= d and o.created_at < d + interval '1 day')::int orders,
      (select coalesce(sum(o.total_amount),0) from public.orders o where o.status <> 'cancelled' and o.created_at >= d and o.created_at < d + interval '1 day') revenue
    from generate_series(date_trunc('day', p_from), date_trunc('day', p_to), interval '1 day') d
  ), category_behavior as (
    select category,
      count(*) filter (where event_type='product_view')::int views,
      count(*) filter (where event_type='add_to_cart')::int cart_adds
    from public.analytics_events where created_at between p_from and p_to and category is not null group by category
  ), category_sales as (
    select oi.product_category category, count(distinct oi.order_id)::int orders, coalesce(sum(oi.line_total),0) revenue
    from public.order_items oi join public.orders o on o.id=oi.order_id
    where o.created_at between p_from and p_to and o.status <> 'cancelled' and oi.product_category is not null group by oi.product_category
  ), category_report as (
    select c.category, coalesce(b.views,0) views, coalesce(b.cart_adds,0) cart_adds, coalesce(s.orders,0) orders, coalesce(s.revenue,0) revenue
    from (values ('dates'),('honey'),('nuts'),('spices'),('food'),('oils')) c(category)
    left join category_behavior b on b.category=c.category left join category_sales s on s.category=c.category
  )
  select jsonb_build_object(
    'kpis', jsonb_build_object(
      'visitors', (select count(distinct session_id) from public.analytics_events where event_type='page_view' and session_id is not null and created_at between p_from and p_to),
      'product_views', (select count(*) from public.analytics_events where event_type='product_view' and created_at between p_from and p_to),
      'cart_adds', (select count(*) from public.analytics_events where event_type='add_to_cart' and created_at between p_from and p_to),
      'orders', (select count(*) from public.orders where created_at between p_from and p_to),
      'revenue', (select coalesce(sum(total_amount),0) from public.orders where status <> 'cancelled' and created_at between p_from and p_to),
      'conversion_rate', round(coalesce((select count(*) from public.orders where created_at between p_from and p_to) * 100.0 / nullif((select count(distinct session_id) from public.analytics_events where event_type='page_view' and session_id is not null and created_at between p_from and p_to),0),0),1)
    ),
    'daily', (select coalesce(jsonb_agg(row_to_json(d) order by d."day"), '[]'::jsonb) from daily d),
    'products', (select coalesce(jsonb_agg(row_to_json(p) order by revenue desc, ordered_units desc, views desc), '[]'::jsonb) from product_report p),
    'categories', (select coalesce(jsonb_agg(row_to_json(c) order by revenue desc, views desc), '[]'::jsonb) from category_report c),
    'opportunities', (select coalesce(jsonb_agg(row_to_json(o)), '[]'::jsonb) from (
      select product_id,name,name_en,name_fr,views,cart_adds,orders,
        case when views >= 5 and cart_adds * 10 < views then 'high_views_low_carts' else 'high_carts_low_orders' end reason
      from product_report
      where (views >= 5 and cart_adds * 10 < views) or (cart_adds >= 3 and orders * 5 < cart_adds)
      order by views desc, cart_adds desc limit 10
    ) o)
  ) into result;
  return result;
end;
$$;

revoke all on function public.admin_analytics_report(timestamptz,timestamptz) from public, anon;
grant execute on function public.admin_analytics_report(timestamptz,timestamptz) to authenticated;

-- Deny-by-default RLS.
alter table public.products enable row level security;
alter table public.advertisements enable row level security;
alter table public.gallery enable row level security;
alter table public.contacts enable row level security;
alter table public.admin_users enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.analytics_events enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.rate_limit_buckets enable row level security;

do $$ declare policy_record record; begin
  for policy_record in select schemaname, tablename, policyname from pg_policies where schemaname='public' and tablename in ('products','advertisements','gallery','contacts','admin_users','orders','order_items','analytics_events','admin_audit_logs','rate_limit_buckets') loop
    execute format('drop policy if exists %I on %I.%I', policy_record.policyname, policy_record.schemaname, policy_record.tablename);
  end loop;
end $$;

create policy products_public_read on public.products for select to anon, authenticated using (true);
create policy products_admin_insert on public.products for insert to authenticated with check (public.is_admin());
create policy products_admin_update on public.products for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy products_admin_delete on public.products for delete to authenticated using (public.is_admin());
create policy advertisements_public_read on public.advertisements for select to anon, authenticated using (true);
create policy advertisements_admin_insert on public.advertisements for insert to authenticated with check (public.is_admin());
create policy advertisements_admin_update on public.advertisements for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy advertisements_admin_delete on public.advertisements for delete to authenticated using (public.is_admin());
create policy gallery_public_read on public.gallery for select to anon, authenticated using (true);
create policy gallery_admin_insert on public.gallery for insert to authenticated with check (public.is_admin());
create policy gallery_admin_update on public.gallery for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy gallery_admin_delete on public.gallery for delete to authenticated using (public.is_admin());
create policy contacts_admin_read on public.contacts for select to authenticated using (public.is_admin());
create policy contacts_admin_delete on public.contacts for delete to authenticated using (public.is_admin());
create policy admin_users_self_read on public.admin_users for select to authenticated using (user_id = auth.uid() and public.is_admin());
create policy orders_admin_read on public.orders for select to authenticated using (public.is_admin());
create policy orders_admin_update on public.orders for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy order_items_admin_read on public.order_items for select to authenticated using (public.is_admin());
create policy analytics_admin_read on public.analytics_events for select to authenticated using (public.is_admin());
create policy audit_admin_read on public.admin_audit_logs for select to authenticated using (public.is_admin());

revoke all on public.products, public.advertisements, public.gallery, public.contacts, public.admin_users,
  public.orders, public.order_items, public.analytics_events, public.admin_audit_logs, public.rate_limit_buckets from anon, authenticated;
grant select on public.products, public.advertisements, public.gallery to anon, authenticated;
grant select, insert, update, delete on public.products, public.advertisements, public.gallery to authenticated;
grant select, delete on public.contacts to authenticated;
grant select, update on public.orders to authenticated;
grant select on public.order_items to authenticated;
grant select on public.admin_users, public.analytics_events, public.admin_audit_logs to authenticated;
grant all on public.products, public.advertisements, public.gallery, public.contacts, public.admin_users,
  public.orders, public.order_items, public.analytics_events, public.admin_audit_logs, public.rate_limit_buckets to service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;

-- Public-read, admin-write gallery Storage bucket.
insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('gallery', 'gallery', true, 26214400, array['image/jpeg','image/png','image/webp','image/avif','video/mp4','video/webm'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists gallery_objects_public_read on storage.objects;
drop policy if exists gallery_objects_admin_insert on storage.objects;
drop policy if exists gallery_objects_admin_update on storage.objects;
drop policy if exists gallery_objects_admin_delete on storage.objects;
create policy gallery_objects_public_read on storage.objects for select to anon, authenticated using (bucket_id = 'gallery');
create policy gallery_objects_admin_insert on storage.objects for insert to authenticated with check (bucket_id = 'gallery' and public.is_admin());
create policy gallery_objects_admin_update on storage.objects for update to authenticated using (bucket_id = 'gallery' and public.is_admin()) with check (bucket_id = 'gallery' and public.is_admin());
create policy gallery_objects_admin_delete on storage.objects for delete to authenticated using (bucket_id = 'gallery' and public.is_admin());

-- Keep the rate-limit table compact when a scheduler calls this function.
create or replace function public.prune_rate_limit_buckets()
returns void language sql security definer set search_path = public, pg_catalog
as $$ delete from public.rate_limit_buckets where window_started_at < now() - interval '2 days'; $$;
revoke all on function public.prune_rate_limit_buckets() from public, anon, authenticated;
grant execute on function public.prune_rate_limit_buckets() to service_role;
