import React, { useState } from 'react';
import { Pencil } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useLanguage } from '@/contexts/LanguageContext';
import { useAsync } from '@/hooks/useAsync';
import { deleteRow, listAdminRows, saveAdvertisement } from '@/services/adminService';
import { AdminBusy, AdminError, AdminNotice, AdminPageHeader, ConfirmDeleteButton } from '@/components/admin/AdminCommon';

const blank = { id: null, image_url: '', link: '' };
export default function AdvertisementsAdmin() {
  const { t, language } = useLanguage(); const rows = useAsync(() => listAdminRows('advertisements'), []); const [form, setForm] = useState(blank); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(null);
  function edit(item = blank) { setForm({ ...blank, ...item, link: item.link || '' }); setOpen(true); setNotice(null); }
  async function submit(event) { event.preventDefault(); setBusy(true); try { await saveAdvertisement(form); setOpen(false); await rows.reload(); setNotice({ type: 'success', message: t('success') }); } catch { setNotice({ type: 'error', message: t('unable') }); } finally { setBusy(false); } }
  async function remove(id) { setBusy(true); try { await deleteRow('advertisements', id); await rows.reload(); setNotice({ type: 'success', message: t('success') }); } catch { setNotice({ type: 'error', message: t('unable') }); } finally { setBusy(false); } }
  return <><AdminPageHeader title={t('advertisements')} onAdd={() => edit()} addLabel={t('addAdvertisement')} /><AdminNotice state={notice} />{open && <form onSubmit={submit} className="surface-card mb-7 mt-4 grid gap-5 p-6"><h2 className="text-xl font-bold">{form.id ? t('editAdvertisement') : t('addAdvertisement')}</h2><div><label className="form-label" htmlFor="ad-image">{t('imageUrl')}</label><input id="ad-image" className="form-control" type="url" required maxLength="1000" dir="ltr" value={form.image_url} onChange={(event) => setForm({ ...form, image_url: event.target.value })} /></div><div><label className="form-label" htmlFor="ad-link">{t('link')}</label><input id="ad-link" className="form-control" type="url" maxLength="1000" dir="ltr" value={form.link} onChange={(event) => setForm({ ...form, link: event.target.value })} /></div>{form.image_url && <img src={form.image_url} alt={t('preview')} className="max-h-52 rounded-xl object-cover" />}<div className="flex gap-3"><Button disabled={busy}>{t('save')}</Button><Button type="button" variant="outline" onClick={() => setOpen(false)}>{t('cancel')}</Button></div></form>}{rows.status === 'loading' && <AdminBusy />}{rows.status === 'error' && <AdminError onRetry={rows.reload} />}{rows.status === 'success' && <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>{t('preview')}</th><th>{t('link')}</th><th>{t('date')}</th><th>{t('actions')}</th></tr></thead><tbody>{rows.data.map((item) => <tr key={item.id}><td><img src={item.image_url} alt="" className="h-20 w-36 rounded-lg object-cover" /></td><td><span className="block max-w-sm truncate" dir="ltr">{item.link || '—'}</span></td><td>{new Date(item.created_at).toLocaleDateString(language)}</td><td><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => edit(item)}><Pencil className="h-4 w-4" /><span className="sr-only">{t('edit')}</span></Button><ConfirmDeleteButton disabled={busy} onConfirm={() => remove(item.id)} /></div></td></tr>)}{rows.data.length === 0 && <tr><td colSpan="4" className="text-center text-muted-foreground">{t('noData')}</td></tr>}</tbody></table></div>}</>;
}
