import React, { useMemo, useState } from 'react';
import { useLanguage } from '@/contexts/LanguageContext';
import { formatMoney } from '@/lib/catalog';
import { useAsync } from '@/hooks/useAsync';
import { listAdminRows, updateOrderStatus } from '@/services/adminService';
import { AdminBusy, AdminError, AdminNotice, AdminPageHeader } from '@/components/admin/AdminCommon';

const statuses = ['new', 'confirmed', 'preparing', 'completed', 'cancelled'];
export default function OrdersAdmin() {
  const { t, language } = useLanguage(); const rows = useAsync(() => listAdminRows('orders', '*,order_items(*)'), []); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('all'); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [busy, setBusy] = useState(null); const [notice, setNotice] = useState(null);
  const filtered = useMemo(() => (rows.data || []).filter((order) => { const date = order.created_at.slice(0, 10); return (!search || [order.id, order.customer_name, order.customer_phone].join(' ').toLowerCase().includes(search.toLowerCase())) && (filter === 'all' || order.status === filter) && (!from || date >= from) && (!to || date <= to); }), [filter, from, rows.data, search, to]);
  async function changeStatus(id, status) { setBusy(id); try { await updateOrderStatus(id, status); await rows.reload(); setNotice({ type: 'success', message: t('success') }); } catch { setNotice({ type: 'error', message: t('unable') }); } finally { setBusy(null); } }
  return <><AdminPageHeader title={t('orders')} /><AdminNotice state={notice} /><div className="mb-6 mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><input value={search} onChange={(event) => setSearch(event.target.value)} className="form-control" placeholder={t('searchAdmin')} /><select value={filter} onChange={(event) => setFilter(event.target.value)} className="form-control"><option value="all">{t('all')}</option>{statuses.map((status) => <option key={status} value={status}>{t(`status_${status}`)}</option>)}</select><label className="text-sm">{t('fromDate')}<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} className="form-control mt-1" /></label><label className="text-sm">{t('toDate')}<input type="date" value={to} onChange={(event) => setTo(event.target.value)} className="form-control mt-1" /></label></div>{rows.status === 'loading' && <AdminBusy />}{rows.status === 'error' && <AdminError onRetry={rows.reload} />}{rows.status === 'success' && <div className="grid gap-4">{filtered.map((order) => <article key={order.id} className="surface-card p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row"><div><h2 className="text-xl font-bold">#{order.id} — {order.customer_name}</h2><div className="mt-1 flex flex-wrap gap-x-5 gap-y-1 text-sm text-muted-foreground"><a dir="ltr" href={`tel:${order.customer_phone}`}>{order.customer_phone}</a><span>{new Date(order.created_at).toLocaleString(language)}</span><strong className="text-primary" dir="ltr">{formatMoney(order.total_amount, language)}</strong></div></div><label className="text-sm font-semibold">{t('status')}<select value={order.status} disabled={busy === order.id} onChange={(event) => changeStatus(order.id, event.target.value)} className="form-control mt-1 min-w-44">{statuses.map((status) => <option key={status} value={status}>{t(`status_${status}`)}</option>)}</select></label></div><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_280px]"><ul className="divide-y divide-border rounded-xl bg-muted/45 px-4">{(order.order_items || []).map((item) => <li key={item.id} className="flex justify-between gap-4 py-3 text-sm"><span>{item.product_name} × {item.quantity}</span><span dir="ltr">{formatMoney(item.line_total, language)}</span></li>)}</ul><dl className="grid content-start gap-2 text-sm"><div><dt className="font-semibold">{t('addressTitle')}</dt><dd className="mt-1 text-muted-foreground">{order.customer_address || '—'}</dd></div><div><dt className="font-semibold">{t('notes')}</dt><dd className="mt-1 whitespace-pre-wrap text-muted-foreground">{order.notes || '—'}</dd></div></dl></div></article>)}{filtered.length === 0 && <p className="surface-card p-6 text-center text-muted-foreground">{t('noData')}</p>}</div>}</>;
}
